import { designTokens } from './src/theme/design-tokens.js';

/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: ['class'],
  theme: {
    extend: {
      colors: {
        // Primary (Teal - 60% usage)
        primary: {
          DEFAULT: designTokens.colors.primary.DEFAULT,
          foreground: designTokens.colors.primary.foreground,
          light: designTokens.colors.primary.light,
          dark: designTokens.colors.primary.dark,
          50: designTokens.colors.primary[50],
          100: designTokens.colors.primary[100],
          200: designTokens.colors.primary[200],
          300: designTokens.colors.primary[300],
          400: designTokens.colors.primary[400],
          500: designTokens.colors.primary[500],
          600: designTokens.colors.primary[600],
          700: designTokens.colors.primary[700],
          800: designTokens.colors.primary[800],
          900: designTokens.colors.primary[900],
        },
        // Secondary (Sage Green - 30% usage)
        secondary: {
          DEFAULT: designTokens.colors.secondary.DEFAULT,
          foreground: designTokens.colors.secondary.foreground,
          light: designTokens.colors.secondary.light,
          dark: designTokens.colors.secondary.dark,
          50: designTokens.colors.secondary[50],
          100: designTokens.colors.secondary[100],
          200: designTokens.colors.secondary[200],
          300: designTokens.colors.secondary[300],
          400: designTokens.colors.secondary[400],
          500: designTokens.colors.secondary[500],
          600: designTokens.colors.secondary[600],
          700: designTokens.colors.secondary[700],
          800: designTokens.colors.secondary[800],
          900: designTokens.colors.secondary[900],
        },
        // Accent (Maroon - 10% usage)
        accent: {
          DEFAULT: designTokens.colors.accent.DEFAULT,
          foreground: designTokens.colors.accent.foreground,
          light: designTokens.colors.accent.light,
          dark: designTokens.colors.accent.dark,
          50: designTokens.colors.accent[50],
          100: designTokens.colors.accent[100],
          200: designTokens.colors.accent[200],
          300: designTokens.colors.accent[300],
          400: designTokens.colors.accent[400],
          500: designTokens.colors.accent[500],
          600: designTokens.colors.accent[600],
          700: designTokens.colors.accent[700],
          800: designTokens.colors.accent[800],
          900: designTokens.colors.accent[900],
        },
        // Semantic Colors
        success: {
          DEFAULT: designTokens.colors.success.DEFAULT,
          foreground: designTokens.colors.success.foreground,
          50: designTokens.colors.success[50],
          500: designTokens.colors.success[500],
          600: designTokens.colors.success[600],
          700: designTokens.colors.success[700],
        },
        warning: {
          DEFAULT: designTokens.colors.warning.DEFAULT,
          foreground: designTokens.colors.warning.foreground,
          50: designTokens.colors.warning[50],
          500: designTokens.colors.warning[500],
          600: designTokens.colors.warning[600],
          700: designTokens.colors.warning[700],
        },
        error: {
          DEFAULT: designTokens.colors.error.DEFAULT,
          foreground: designTokens.colors.error.foreground,
          50: designTokens.colors.error[50],
          500: designTokens.colors.error[500],
          600: designTokens.colors.error[600],
          700: designTokens.colors.error[700],
        },
        destructive: designTokens.colors.error,
        // UI Colors
        background: designTokens.colors.background,
        foreground: designTokens.colors.foreground,
        card: {
          DEFAULT: designTokens.colors.card,
          foreground: designTokens.colors['card-foreground'],
        },
        popover: {
          DEFAULT: designTokens.colors.card,
          foreground: designTokens.colors['card-foreground'],
        },
        muted: {
          DEFAULT: designTokens.colors.muted,
          foreground: designTokens.colors['muted-foreground'],
        },
        border: designTokens.colors.border,
        input: {
          DEFAULT: designTokens.colors.input,
          background: designTokens.colors['input-background'],
        },
        ring: designTokens.colors.ring,
      },
      spacing: designTokens.spacing,
      borderRadius: designTokens.borderRadius,
      fontFamily: designTokens.typography.fontFamily,
      fontSize: designTokens.typography.fontSize,
      fontWeight: designTokens.typography.fontWeight,
      lineHeight: designTokens.typography.lineHeight,
      letterSpacing: designTokens.typography.letterSpacing,
      boxShadow: designTokens.shadows,
      zIndex: designTokens.zIndex,
      opacity: designTokens.opacity,
      transitionDuration: designTokens.animation.durations,
      transitionTimingFunction: designTokens.animation.easings,
      maxWidth: designTokens.containers,
      screens: designTokens.breakpoints,
    },
  },
  plugins: [],
}
