declare module 'lucide-react' {
  import { ComponentType, SVGProps } from 'react';
  
  export interface LucideProps extends SVGProps<SVGSVGElement> {
    size?: string | number;
    absoluteStrokeWidth?: boolean;
  }
  
  export type LucideIcon = ComponentType<LucideProps>;
  
  // All commonly used icons
  export const AlertTriangle: LucideIcon;
  export const Shield: LucideIcon;
  export const Eye: LucideIcon;
  export const Ban: LucideIcon;
  export const Users: LucideIcon;
  export const Car: LucideIcon;
  export const DollarSign: LucideIcon;
  export const ScanSearch: LucideIcon;
  export const CirclePlus: LucideIcon;
  export const MessageSquare: LucideIcon;
  export const CreditCard: LucideIcon;
  export const UsersRound: LucideIcon;
  export const Zap: LucideIcon;
  export const Target: LucideIcon;
  export const Award: LucideIcon;
  export const BellDot: LucideIcon;
  export const CircleUserRound: LucideIcon;
  export const Languages: LucideIcon;
  export const CheckCircle2: LucideIcon;
  export const Circle: LucideIcon;
  export const TrendingUp: LucideIcon;
  export const Activity: LucideIcon;
  export const Search: LucideIcon;
  export const Filter: LucideIcon;
  export const Download: LucideIcon;
  export const CheckCircle: LucideIcon;
  export const XCircle: LucideIcon;
  export const Clock: LucideIcon;
  export const MapPin: LucideIcon;
  export const MessageSquare: LucideIcon;
  export const Locate: LucideIcon;
  export const CalendarClock: LucideIcon;
  export const UsersRound: LucideIcon;
  export const CircleDollarSign: LucideIcon;
  export const Sparkles: LucideIcon;
  export const MoveRight: LucideIcon;
  export const SlidersHorizontal: LucideIcon;
  export const CircleX: LucideIcon;
  export const Sparkle: LucideIcon;
  export const ShieldCheck: LucideIcon;
  export const Check: LucideIcon;
  export const X: LucideIcon;
  export const Plus: LucideIcon;
  export const Minus: LucideIcon;
  export const Menu: LucideIcon;
  export const Home: LucideIcon;
  export const User: LucideIcon;
  export const Settings: LucideIcon;
  export const Bell: LucideIcon;
  export const Mail: LucideIcon;
  export const Phone: LucideIcon;
  export const Star: LucideIcon;
  export const Heart: LucideIcon;
  export const Share: LucideIcon;
  export const Upload: LucideIcon;
  export const Edit: LucideIcon;
  export const Trash: LucideIcon;
  export const Save: LucideIcon;
  export const Copy: LucideIcon;
  export const ExternalLink: LucideIcon;
  export const ChevronDown: LucideIcon;
  export const ChevronUp: LucideIcon;
  export const ChevronLeft: LucideIcon;
  export const ChevronRight: LucideIcon;
  export const ArrowLeft: LucideIcon;
  export const ArrowRight: LucideIcon;
  export const ArrowUp: LucideIcon;
  export const ArrowDown: LucideIcon;
  export const Info: LucideIcon;
  export const Warning: LucideIcon;
  export const Error: LucideIcon;
  export const Success: LucideIcon;
  export const Loading: LucideIcon;
  export const Refresh: LucideIcon;
  export const Grid: LucideIcon;
  export const List: LucideIcon;
  export const Calendar: LucideIcon;
  export const Image: LucideIcon;
  export const File: LucideIcon;
  export const Folder: LucideIcon;
  export const Lock: LucideIcon;
  export const Unlock: LucideIcon;
  export const Visibility: LucideIcon;
  export const VisibilityOff: LucideIcon;
  export const ThumbsUp: LucideIcon;
  export const ThumbsDown: LucideIcon;
  export const Flag: LucideIcon;
  export const Bookmark: LucideIcon;
  export const Tag: LucideIcon;
  export const Link: LucideIcon;
  export const Unlink: LucideIcon;
  export const Bold: LucideIcon;
  export const Italic: LucideIcon;
  export const Underline: LucideIcon;
  export const Code: LucideIcon;
  export const Quote: LucideIcon;
  export const Heading: LucideIcon;
  export const Paragraph: LucideIcon;
  export const AlignLeft: LucideIcon;
  export const AlignCenter: LucideIcon;
  export const AlignRight: LucideIcon;
  export const AlignJustify: LucideIcon;
  export const Indent: LucideIcon;
  export const Outdent: LucideIcon;
  export const Undo: LucideIcon;
  export const Redo: LucideIcon;
  export const Cut: LucideIcon;
  export const Paste: LucideIcon;
  export const SelectAll: LucideIcon;
  export const Find: LucideIcon;
  export const Replace: LucideIcon;
  export const Print: LucideIcon;
  export const Preview: LucideIcon;
  export const Fullscreen: LucideIcon;
  export const ExitFullscreen: LucideIcon;
  export const Minimize: LucideIcon;
  export const Maximize: LucideIcon;
  export const Close: LucideIcon;
  export const More: LucideIcon;
  export const MoreHorizontal: LucideIcon;
  export const MoreVertical: LucideIcon;
  
  // Export all other icons as a fallback
  const lucideReact: Record<string, LucideIcon>;
  export default lucideReact;
}